baseURL = "https://enclair-jrnl.github.io/enclair-jrnl/"
languageCode = "it-IT"
title = "enclair journal"
theme = "archie"
buildFuture = true
buildDrafts = true

[params]
  mode = "auto"
  subtitle = "little thoughts"
  math = false
  readtime = true

[taxonomies]
  tag = "tags"
